//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill_type()
        {
            this.bill = new HashSet<bill>();
        }
    
        public int type_id { get; set; }
        public string type_name { get; set; }
        public Nullable<bool> task { get; set; }
        public string url { get; set; }
        public Nullable<int> day_due { get; set; }
        public Nullable<int> month_due { get; set; }
        public Nullable<int> year_due { get; set; }
        public Nullable<bool> auto { get; set; }
        public Nullable<decimal> amount_due { get; set; }
        public int frequency_id { get; set; }
        public int payment_method_id { get; set; }
        public int payer_id { get; set; }
        public int status_id { get; set; }
        public string bill_type_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bill { get; set; }
        public virtual frequency frequency { get; set; }
        public virtual payer payer { get; set; }
        public virtual payment_method payment_method { get; set; }
        public virtual status status { get; set; }
    }
}
