//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billsapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class billsappdbEntities : DbContext
    {
        public billsappdbEntities()
            : base("name=billsappdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bill { get; set; }
        public virtual DbSet<bill_type> bill_type { get; set; }
        public virtual DbSet<bills_payers> bills_payers { get; set; }
        public virtual DbSet<bills_payments> bills_payments { get; set; }
        public virtual DbSet<bills_sessions> bills_sessions { get; set; }
        public virtual DbSet<frequency> frequency { get; set; }
        public virtual DbSet<payer> payer { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<payment_method> payment_method { get; set; }
        public virtual DbSet<session> session { get; set; }
        public virtual DbSet<session_deposit> session_deposit { get; set; }
        public virtual DbSet<sessions_payers> sessions_payers { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<users_payers> users_payers { get; set; }
    }
}
