//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bills_payments
    {
        public int bill_id { get; set; }
        public int payment_id { get; set; }
        public int id { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual payment payment { get; set; }
    }
}
