//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions_payers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sessions_payers()
        {
            this.session_deposit = new HashSet<session_deposit>();
        }
    
        public Nullable<decimal> balance_starting { get; set; }
        public Nullable<decimal> balance_remaining { get; set; }
        public Nullable<decimal> bills_sum { get; set; }
        public int session_id { get; set; }
        public int payer_id { get; set; }
        public Nullable<decimal> transfer_amount { get; set; }
    
        public virtual payer payer { get; set; }
        public virtual session session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_deposit> session_deposit { get; set; }
    }
}
