//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_deposit
    {
        public int deposit_id { get; set; }
        public int session_id { get; set; }
        public int payer_id { get; set; }
        public decimal deposit_amount { get; set; }
        public string deposit_note { get; set; }
        public System.DateTime deposit_date { get; set; }
    
        public virtual sessions_payers sessions_payers { get; set; }
    }
}
