//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions_payers
    {
        public int id { get; set; }
        public Nullable<decimal> balance_starting { get; set; }
        public Nullable<decimal> balance_remaining { get; set; }
        public Nullable<decimal> bills_sum { get; set; }
        public int session_id { get; set; }
        public int payer_id { get; set; }
        public Nullable<decimal> transfer_amount { get; set; }
    
        public virtual payer payer { get; set; }
        public virtual session session { get; set; }
    }
}
